### ISSUE TITLE
Wondering when will you release the code?

### ISSUE THREAD

**Issue by jsun57** [BarqueroGerman/BeLFusion#1]
Thanks!

**Comment by BarqueroGerman** [comment]
Thanks for your interest in our work! We will try to upload it before the end of January.

**Comment by jsun57** [comment]
Any updates? Really looking forward to it!!

**Comment by BarqueroGerman** [comment]
Hi @jsun57! Sorry for the delay. The code is almost ready and will be uploaded to this repository **next week**.

**Comment by BarqueroGerman** [comment]
Hi again. We just released the code. Thanks for your patience!
