### ISSUE TITLE
Wondering if we have mm_gt and mm_indces to support load_mmgt() function.

### ISSUE THREAD

**Issue by jsun57** [BarqueroGerman/BeLFusion#3]

**Comment by BarqueroGerman** [comment]
We tried using the multimodal ground truth for training at some stage of the project. However, the idea was discarded, as we felt adding more regularization was unnecessary. 

Anyway, we removed most parts of the code needed for those arguments to work, and our intention was to fully remove them. I don't have such files anymore, but they simply contained the list of indices of the segments inside their multimodal ground truth. The files shouldn't be difficult to generate using the "get_multimodal_gt" function used for MMADE and MMFDE computation in the evaluation scripts.
