### ISSUE TITLE
AMASS files corrupted

### ISSUE THREAD

**Issue by Evm7** [BarqueroGerman/BeLFusion#4]
Dear German,

Thanks for your nice work and documentation. When following your installation, I am encountering that running...
`python -m data_loader.parsers.amass --gpu`

... raises lots of messages regarding files being corrupted.
`1957it [01:38, 23.22it/s]WARNING: we skip 'BMLmovi/Subject_5_F_MoSh/shape.npz' because it is corrupted (no framerate)`

I have tried to re-download again these tar files from AMASS, but the issue is still there.
Is that behavior expected or did you encounter also that?

Again, congratulations for your nice results

**Comment by BarqueroGerman** [comment]
Hi Esteve!

Thank you for your interest in our work! Those warning messages are expected, because motion sequences/files without metadata information about the framerate were filtered out to prevent injecting undesired noise to the dataset. Just ignore them and proceed :)

German Barquero
