### ISSUE TITLE
Wondering how to train baselines

### ISSUE THREAD

**Issue by Haodong-Yan** [BarqueroGerman/BeLFusion#6]
could you please release codes for training baseline models like Dlow?  I want to compare them with your method on a new dataset

**Comment by BarqueroGerman** [comment]
Hi! Thanks for your interest in our work! To train the baselines on AMASS, we used their respective public code repositories. We imported our data loader and tuned the hyperparameters as described in our paper. You can look at their code in the following repositories:

- DLow & TPK: https://github.com/Khrylx/DLow
- Motron: https://github.com/TUM-AAS/motron-cvpr22
- GSPS: https://github.com/wei-mao-2019/gsps
- DivSampling: https://github.com/Droliven/diverse_sampling
