### ISSUE TITLE
Missing class "PoseTransformerTemporal"

### ISSUE THREAD

**Issue by SodaCoder** [BarqueroGerman/BeLFusion#7]
Hello,

The file defining the class "PoseTransformerTemporal" seems to be missing. Could you upload it?

Thanks,
Sourav

**Comment by BarqueroGerman** [comment]
Hi SodaCoder,

The GDUnet class was old code unsupported in the current state of the project. It was later adapted for the latent diffusion in the GDUnet_Latent. I just removed it. In any case, if you are curious, the PoseTransformerTemporal was brought from https://github.com/zczcwh/PoseFormer.

Thanks for your interest in our work!

German
