### ISSUE TITLE
GDUnet_Latent or GDUnet_Latent_vSum?

### ISSUE THREAD

**Issue by SodaCoder** [BarqueroGerman/BeLFusion#8]
Hello,

I would like to implement Latent Diffusion for pedestrian trajectory forecasting. I am wondering which U-Net class to adapt from. Is it GDUnet_Latent or GDUnet_Latent_vSum?

Awaiting an early response. 

Thanks,
Sourav

**Comment by BarqueroGerman** [comment]
Hi Sourav,

You should use GDUnet_Latent. The "vSum" version was part of an ablation with a different conditioning method. In particular, you should check: LatentUNetMatcher. This wrapper denoises the noisy latent codes into denoised behavior codes.
