### ISSUE TITLE
how to train AMASS data sets on GSPS and DiverseSampling

### ISSUE THREAD

**Issue by wangtingyu-gjw** [BarqueroGerman/BeLFusion#9]
Hello, how to train AMASS data sets on GSPS and DiverseSampling, can the scripts related to this part be made public? Thank you very much!

**Comment by BarqueroGerman** [comment]
Hi! 

Thank you for your interest in our work. For GSPS and DiverseSampling baselines on AMASS, we shared the weights of our trained models. For replicating our training, you can import our data loader for AMASS to make it work with the particularities of each of the baselines (GSPS/DivSamp). We don't plan to release them as it is not part of our main work and would require a lot of effort and time. But I will gladly assist you if you have any questions about the process.

German

**Comment by wangtingyu-gjw** [comment]
Thanks！
